# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 08:21
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django_extensions.db.fields
import officina.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'distribution area',
                'verbose_name_plural': 'distribution areas',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.CharField(blank=True, max_length=100)),
                ('workflow_state', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, null=True, verbose_name='workflow')),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('given_name', 'family_name'), unique=True)),
                ('presentation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
            bases=(models.Model, officina.models.HasWorkflow),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True, help_text='Is this product publicly visible.', verbose_name='Active')),
                ('import_id', models.CharField(blank=True, max_length=100)),
                ('workflow_state', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='workflow')),
                ('publication_state', models.IntegerField(choices=[(0, 'Planned'), (1, 'In press'), (2, 'In distribution'), (3, 'Out of print')], default=1, verbose_name='publication')),
                ('product_name', models.CharField(max_length=255, verbose_name='Book Title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('product_name',), unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, verbose_name='Book Presentation')),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('pde', models.CharField(blank=True, max_length=10, verbose_name='PDE')),
                ('year', models.CharField(blank=True, max_length=100)),
                ('pages', models.CharField(blank=True, max_length=100)),
                ('unit_price', django.db.models.fields.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Net price for this product', max_digits=30)),
                ('small_image', models.ImageField(blank=True, upload_to='images/')),
                ('medium_image', models.ImageField(blank=True, upload_to='images/')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
            bases=(models.Model, officina.models.HasWorkflow),
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Author'), (2, 'Editor')], default=1)),
                ('role_prefix', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to='officina.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='officina.Book')),
            ],
            options={
                'verbose_name': 'book author relationship',
                'verbose_name_plural': 'book author relationships',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_state', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='workflow')),
                ('title', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True)),
                ('street_address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'distributor',
                'verbose_name_plural': 'distributors',
            },
            bases=(models.Model, officina.models.HasWorkflow),
        ),
        migrations.CreateModel(
            name='DistributorArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_distributor', to='officina.Area')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_area', to='officina.Distributor')),
            ],
            options={
                'verbose_name': 'distributor area',
                'verbose_name_plural': 'distributor areas',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.CharField(blank=True, max_length=100)),
                ('workflow_state', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, null=True, verbose_name='workflow')),
                ('title', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('format', models.CharField(blank=True, max_length=200)),
                ('presentation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'book series',
                'verbose_name_plural': 'book series',
            },
            bases=(models.Model, officina.models.HasWorkflow),
        ),
        migrations.AddField(
            model_name='distributor',
            name='areas',
            field=models.ManyToManyField(blank=True, through='officina.DistributorArea', to='officina.Area'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, through='officina.BookAuthor', to='officina.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_officina.book_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_books', to='officina.Series'),
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, through='officina.BookAuthor', to='officina.Book'),
        ),
        migrations.AddField(
            model_name='area',
            name='distributors',
            field=models.ManyToManyField(blank=True, through='officina.DistributorArea', to='officina.Distributor'),
        ),
    ]
